[options]
; This is the password that allows database operations:
; admin_passwd = admin
addons_path = /opt/odoo18/custom_addons,/opt/odoo18/addons
db_host = False
db_port = False
db_user = viruco
db_password = Manatar#2020$
;addons_path = /usr/lib/python3/dist-packages/odoo/addons
default_productivity_apps = True
